application: pigfi
version: 1
runtime: python
api_version: 1

handlers:
- url: /media
  static_dir: media

- url: /favicon.ico
  static_files: media/images/favicon.ico
  upload: static/(.*)

- url: /.*
  script: main.py

  